ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "costConfirmationThreshold" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "costConfirmationEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AIUsage" ADD COLUMN IF NOT EXISTS "confirmationRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AIUsage" ADD COLUMN IF NOT EXISTS "confirmed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AIJob" ADD COLUMN IF NOT EXISTS "model" TEXT;
