import { Telegraf, Markup, session } from 'telegraf';import { env } from '@moones/config';import { formatToman, taskLabel } from '@moones/shared';
if(!env.TELEGRAM_BOT_TOKEN){console.log('TELEGRAM_BOT_TOKEN is empty; bot idle.');process.exit(0)}
const bot=new Telegraf(env.TELEGRAM_BOT_TOKEN);bot.use(session());const api=env.API_URL||'http://localhost:4000';const menu=Markup.keyboard([['💬 چت با AI','🎨 ساخت عکس'],['🎬 ساخت ویدیو','💰 کیف پول'],['📊 تاریخچه مصرف','❓ راهنما']]).resize();
async function post(path:string,body:any){return fetch(api+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json())}async function get(path:string){return fetch(api+path).then(r=>r.json())}async function user(ctx:any){return post('/api/bot/user',{telegramId:ctx.from.id,username:ctx.from.username,firstName:ctx.from.first_name,lastName:ctx.from.last_name,languageCode:ctx.from.language_code})}
bot.start(async ctx=>{const u=await user(ctx);await ctx.reply(`سلام 👋\nبه مونِس AI خوش اومدی.\nاینجا می‌تونی خیلی ساده با هوش مصنوعی چت کنی، عکس بسازی یا ویدیو تولید کنی.\nلازم نیست مدل‌ها رو بشناسی؛ فقط کاری که می‌خوای رو انتخاب کن.\n\nموجودی کیف پول: ${formatToman(u.walletBalance)} تومان`,menu)});
bot.hears('💬 چت با AI',ctx=>{(ctx.session as any).mode='chat';ctx.reply('پیامت رو بفرست.\nمن خودم مدل مناسب رو انتخاب می‌کنم.',menu)});bot.hears('🎨 ساخت عکس',ctx=>{(ctx.session as any).mode='image';ctx.reply('توضیح بده چه عکسی می‌خوای بسازم.\nمثلاً: «یک پوستر مینیمال برای کافه با رنگ‌های گرم»',menu)});bot.hears('🎬 ساخت ویدیو',ctx=>{(ctx.session as any).mode='video';ctx.reply('توضیح بده چه ویدیویی می‌خوای بسازم.\nبرای نتیجه بهتر، کوتاه و واضح بنویس.',menu)});
bot.hears('💰 کیف پول',async ctx=>{const u=await user(ctx);ctx.reply(`موجودی کیف پول: ${formatToman(u.walletBalance)} تومان`,Markup.keyboard([['شارژ ۵۰,۰۰۰ تومان','شارژ ۱۰۰,۰۰۰ تومان'],['شارژ ۲۵۰,۰۰۰ تومان','شارژ ۵۰۰,۰۰۰ تومان'],['مبلغ دلخواه','تاریخچه تراکنش‌ها'],['بازگشت']]).resize())});
bot.hears('📊 تاریخچه مصرف',async ctx=>{const u=await user(ctx);const h=await get(`/api/bot/history/${u.id}`);const lines=h.items?.length?h.items.map((x:any)=>`• ${taskLabel(x.taskType)} — ${formatToman(x.finalUserCharge||0)} تومان`).join('\n'):'هنوز مصرفی ثبت نشده.';ctx.reply(lines,menu)});
bot.hears('❓ راهنما',ctx=>ctx.reply('• کیف پول رو شارژ می‌کنی\n• هر بار استفاده، هزینه از کیف پول کم میشه\n• هزینه بسته به نوع کار و حجم درخواست فرق داره\n• قبل از کارهای گرون، ازت تایید می‌گیریم\n• لازم نیست مدل‌های AI رو بشناسی',menu));bot.hears('بازگشت',ctx=>{(ctx.session as any).mode=undefined;ctx.reply('به منوی اصلی برگشتی.',menu)});
bot.action(/confirm:(chat|image|video):(.+)/,async ctx=>{const u=await user(ctx);const task=(ctx.match as any)[1];const prompt=decodeURIComponent((ctx.match as any)[2]);const r=await post('/api/bot/run',{userId:u.id,taskType:task,prompt,confirm:true});await sendResult(ctx,r)});
async function sendResult(ctx:any,r:any){if(r.error==='insufficient')return ctx.reply('موجودی کیف پولت کافی نیست.\nبرای ادامه باید کیف پولت رو شارژ کنی.',Markup.keyboard([['💰 شارژ کیف پول'],['بازگشت']]).resize());if(r.confirmRequired)return ctx.reply(`این درخواست ممکنه کمی پرهزینه‌تر باشه.\nهزینه تقریبی: ${formatToman(r.min)} تا ${formatToman(r.max)} تومان`,Markup.inlineKeyboard([[Markup.button.callback('✅ ادامه بده',`confirm:chat:${encodeURIComponent((ctx.session as any).lastPrompt)}`)],[Markup.button.callback('⚡ ارزان‌تر انجام بده','cheap')]]));if(r.type==='chat') await ctx.reply(`${r.text}\n\nهزینه: ${formatToman(r.cost)} تومان\nمانده: ${formatToman(r.balance)} تومان`,menu);if(r.type==='image'){await ctx.replyWithPhoto(r.url);await ctx.reply(`هزینه: ${formatToman(r.cost)} تومان\nمانده: ${formatToman(r.balance)} تومان`,menu)}if(r.type==='video'){await ctx.reply('درخواستت ثبت شد. بعد از آماده شدن، همین‌جا برات ارسال می‌کنم.');await ctx.replyWithVideo(r.url);await ctx.reply(`هزینه: ${formatToman(r.cost)} تومان\nمانده: ${formatToman(r.balance)} تومان`,menu)}}
bot.on('text',async ctx=>{const mode=(ctx.session as any).mode;if(!mode)return;const u=await user(ctx);(ctx.session as any).lastPrompt=ctx.message.text;const r=await post('/api/bot/run',{userId:u.id,taskType:mode,prompt:ctx.message.text,confirm:false});if(r.confirmRequired&&mode==='video')return ctx.reply(`ساخت ویدیو هزینه بیشتری دارد.\nهزینه تقریبی: ${formatToman(r.min)} تا ${formatToman(r.max)} تومان`,Markup.inlineKeyboard([[Markup.button.callback('✅ ساخت ویدیو',`confirm:video:${encodeURIComponent(ctx.message.text)}`)],[Markup.button.callback('بازگشت','back')]]));await sendResult(ctx,r)});
bot.launch();console.log('Moones AI bot started');process.once('SIGINT',()=>bot.stop('SIGINT'));process.once('SIGTERM',()=>bot.stop('SIGTERM'));
