import { Telegraf, Markup, session } from 'telegraf';import { env } from '@moones/config';import { formatToman, taskLabel } from '@moones/shared';
if(!env.TELEGRAM_BOT_TOKEN){console.log('TELEGRAM_BOT_TOKEN is empty; bot idle.');process.exit(0)}
const bot=new Telegraf(env.TELEGRAM_BOT_TOKEN);bot.use(session({ defaultSession: () => ({ mode: 'chat' }) }));const api=env.API_URL||'http://localhost:4000';const menu=Markup.keyboard([['💬 چت با AI','🎨 ساخت عکس'],['🎬 ساخت ویدیو','💰 کیف پول'],['📊 تاریخچه مصرف','❓ راهنما']]).resize();
async function post(path:string,body:any){const r=await fetch(api+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json()}async function get(path:string){return fetch(api+path).then(r=>r.json())}async function user(ctx:any){return post('/api/bot/user',{telegramId:ctx.from.id,username:ctx.from.username,firstName:ctx.from.first_name,lastName:ctx.from.last_name,languageCode:ctx.from.language_code})}
bot.start(async ctx=>{const u=await user(ctx);await ctx.reply(`سلام 👋\nبه اوستا خوش اومدی.\nاینجا می‌تونی خیلی ساده با هوش مصنوعی چت کنی، عکس بسازی یا ویدیو تولید کنی.\nلازم نیست مدل‌ها رو بشناسی؛ اوستا خودش مسیر مناسب رو انتخاب می‌کنه.\n\nموجودی کیف پول: ${formatToman(u.walletBalance)} تومان`,menu)});
bot.hears('💬 چت با AI',ctx=>{(ctx.session as any).mode='chat';ctx.reply('پیامت رو بفرست. اوستا خودش بهترین مدل فعال رو انتخاب می‌کنه.',menu)});bot.hears('🎨 ساخت عکس',ctx=>{(ctx.session as any).mode='image';ctx.reply('توضیح بده چه عکسی می‌خوای بسازم. اگر سرویس عکس فعال نباشه همین‌جا بهت می‌گم.',menu)});bot.hears('🎬 ساخت ویدیو',ctx=>{(ctx.session as any).mode='video';ctx.reply('توضیح بده چه ویدیویی می‌خوای بسازم. اگر سرویس ویدیو فعال نباشه همین‌جا بهت می‌گم.',menu)});
bot.hears('💰 کیف پول',async ctx=>{const u=await user(ctx);ctx.reply(`موجودی کیف پول: ${formatToman(u.walletBalance)} تومان`,Markup.keyboard([['شارژ ۵۰,۰۰۰ تومان','شارژ ۱۰۰,۰۰۰ تومان'],['شارژ ۲۵۰,۰۰۰ تومان','شارژ ۵۰۰,۰۰۰ تومان'],['مبلغ دلخواه','تاریخچه تراکنش‌ها'],['بازگشت']]).resize())});
bot.hears('📊 تاریخچه مصرف',async ctx=>{const u=await user(ctx);const h=await get(`/api/bot/history/${u.id}`);const lines=h.items?.length?h.items.map((x:any)=>`• ${taskLabel(x.taskType)} — ${formatToman(x.finalUserCharge||0)} تومان`).join('\n'):'هنوز مصرفی ثبت نشده.';ctx.reply(lines,menu)});
bot.hears('❓ راهنما',ctx=>ctx.reply('• کیف پول رو شارژ می‌کنی\n• هر بار استفاده موفق، هزینه فقط یک‌بار از کیف پول کم میشه\n• اگر Provider در دسترس نباشه هزینه‌ای کم نمی‌شه\n• قبل از کارهای گرون، ازت تایید می‌گیریم\n• لازم نیست مدل‌های AI رو بشناسی',menu));bot.hears('بازگشت',ctx=>{(ctx.session as any).mode='chat';ctx.reply('به منوی اصلی برگشتی.',menu)});
bot.action(/confirm:(chat|image|video):(.+)/,async ctx=>{try{await ctx.answerCbQuery();const u=await user(ctx);const task=(ctx.match as any)[1];const prompt=decodeURIComponent((ctx.match as any)[2]);const r=await post('/api/bot/run',{userId:u.id,taskType:task,prompt,confirm:true});await sendResult(ctx,r)}catch{await ctx.reply('خطایی رخ داد. لطفاً دوباره تلاش کن.',menu)}});bot.action('back',async ctx=>{await ctx.answerCbQuery();(ctx.session as any).mode='chat';await ctx.reply('به منوی اصلی برگشتی.',menu)});bot.action('cheap',async ctx=>{await ctx.answerCbQuery();await ctx.reply('درخواست لغو شد. می‌تونی متن کوتاه‌تر یا ساده‌تری بفرستی.',menu)});
async function sendResult(ctx:any,r:any){if(r.error==='insufficient')return ctx.reply(`موجودی کیف پولت کافی نیست.\nموجودی: ${formatToman(r.balance)} تومان\nهزینه تقریبی: ${formatToman(r.estimate)} تومان`,Markup.keyboard([['💰 کیف پول'],['بازگشت']]).resize());if(r.error==='disabled'||r.error==='provider_unavailable')return ctx.reply(r.message||'این قابلیت فعلاً در دسترس نیست و هزینه‌ای از کیف پولت کم نشد.',menu);if(r.confirmRequired)return ctx.reply(`این درخواست ممکنه کمی پرهزینه‌تر باشه.\nهزینه تقریبی: ${formatToman(r.min)} تا ${formatToman(r.max)} تومان`,Markup.inlineKeyboard([[Markup.button.callback('✅ ادامه بده',`confirm:${(ctx.session as any).mode||'chat'}:${encodeURIComponent((ctx.session as any).lastPrompt||'')}`)],[Markup.button.callback('⚡ ارزان‌تر انجام بده','cheap')]]));if(r.type==='chat') await ctx.reply(`${r.text}\n\nهزینه: ${formatToman(r.cost)} تومان\nمانده: ${formatToman(r.balance)} تومان`,menu);else if(r.type==='image'){await ctx.replyWithPhoto(r.url);await ctx.reply(`هزینه: ${formatToman(r.cost)} تومان\nمانده: ${formatToman(r.balance)} تومان`,menu)}else if(r.type==='video'){await ctx.reply(r.message||'درخواستت ثبت شد. بعد از آماده شدن، همین‌جا برات ارسال می‌کنم.',menu)}else await ctx.reply('پاسخ نامشخص دریافت شد؛ هزینه‌ای کم نشده است.',menu)}
bot.on('text',async ctx=>{const mode=(ctx.session as any).mode||'chat';const u=await user(ctx);(ctx.session as any).lastPrompt=ctx.message.text;const r=await post('/api/bot/run',{userId:u.id,taskType:mode,prompt:ctx.message.text,confirm:false});await sendResult(ctx,r)});
bot.launch();console.log('Osta bot started');process.once('SIGINT',()=>bot.stop('SIGINT'));process.once('SIGTERM',()=>bot.stop('SIGTERM'));
