import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import rateLimit from '@fastify/rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { prisma, LedgerType, PaymentReceiptStatus } from '@moones/db';
import { env } from '@moones/config';
import { adjustWallet, calculatePrice, refund, reserve } from '@moones/billing';
import { getAIProvider, ModelRouter, PromptClassifier, defaultRouterModels, friendlyNoModelMessage } from '@moones/ai';
import { promptPreview } from '@moones/shared';

const app = Fastify({ logger: true });
app.register(cors, { origin: true, credentials: true });
app.register(cookie);
app.register(rateLimit, { max: 120, timeWindow: '1 minute' });
const classifier = new PromptClassifier();
const router = new ModelRouter(classifier);
const sign = (id: string) => jwt.sign({ id }, env.JWT_SECRET, { expiresIn: '7d' });
const safeAdmin = (a: any) => ({ id: a.id, email: a.email, role: a.role });
const trunc = (e: any) => String(e?.message || e || '').replace(process.env.VENICE_API_KEY || '__none__', '[redacted]').slice(0, 1500);
const defaultThreshold = () => Number(process.env.DEFAULT_COST_CONFIRMATION_THRESHOLD_TOMAN || 10000);
const forbiddenMessage = 'اوستا نمی‌تونه برای این نوع محتوای ممنوعه خروجی بسازه. می‌تونی درخواستت رو در چارچوب امن‌تر و غیرآسیب‌زا دوباره بفرستی.';
function adminCookieOptions() { const opts: any = { httpOnly: true, sameSite: 'lax', secure: env.NODE_ENV === 'production', path: '/', maxAge: 7 * 24 * 60 * 60 }; try { if (new URL(process.env.PUBLIC_APP_URL || 'https://ai.moones.top').hostname === 'ai.moones.top') opts.domain = 'ai.moones.top'; } catch {} return opts; }
async function auth(req: any, res: any) { const token = req.cookies?.admin_token || req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.code(401).send({ error: 'unauthorized' }); try { const p = jwt.verify(token, env.JWT_SECRET) as any; req.admin = await prisma.admin.findUniqueOrThrow({ where: { id: p.id } }); } catch { return res.code(401).send({ error: 'unauthorized' }); } }
async function setting(key: string, fallback: any) { const row = await prisma.setting.findUnique({ where: { key } }).catch(() => null); return row?.value ?? fallback; }
function toThreadType(task: string) { return task === 'image' || task === 'video' || task === 'code' || task === 'document' ? task : task === 'file_generation' ? 'document' : 'chat'; }
async function registryModels() { const rows = await prisma.aIModel.findMany({ where: { enabled: true, provider: { enabled: true } }, include: { provider: true, performance: true } }).catch(() => []); if (!rows.length) return defaultRouterModels(); return rows.map((m: any) => ({ provider: m.provider.name, modelId: m.modelId, displayName: m.displayName, enabled: m.enabled, capabilities: m.capabilities || [], taskTypes: m.taskTypes || [], safetyProfiles: m.safetyProfiles || [], qualityScore: m.qualityScore, speedScore: m.speedScore, costScore: m.costScore, persianScore: m.persianScore, codingScore: m.codingScore, imageScore: m.imageScore, videoScore: m.videoScore, priority: m.priority, imageCostUsd: m.imageCostUsd, videoCostUsd: m.videoCostUsd, performance: m.performance?.[0] })); }
async function ensureThread(userId: string, prompt: string, taskType: string, threadId?: string, safetyProfile = 'safe_default') { if (threadId) return prisma.conversationThread.findFirstOrThrow({ where: { id: threadId, userId, archived: false } }); return prisma.conversationThread.create({ data: { userId, title: promptPreview(prompt).slice(0, 60) || 'گفت‌وگوی جدید', type: toThreadType(taskType) as any, safetyProfile } }); }
async function chargeSuccessful(userId: string, usageId: string, taskType: any, estimate: number, providerCost: number, description: string) { return prisma.$transaction(async tx => { const u = await tx.user.findUniqueOrThrow({ where: { id: userId } }); if (u.walletBalance < estimate) throw new Error('INSUFFICIENT_BALANCE'); const after = u.walletBalance - estimate; await tx.walletLedger.create({ data: { userId, type: LedgerType.USAGE_CHARGE, amount: -estimate, balanceBefore: u.walletBalance, balanceAfter: after, description, metadata: { usageId } } }); await tx.user.update({ where: { id: userId }, data: { walletBalance: after } }); await tx.aIUsage.update({ where: { id: usageId }, data: { status: 'completed', finalUserCharge: estimate, providerCost, grossMargin: estimate - providerCost } }); return after; }); }

app.get('/health', async () => ({ ok: true, name: 'Osta' }));
app.post('/api/admin/login', async (req, res) => { const b = z.object({ email: z.string().email(), password: z.string() }).parse(req.body); const a = await prisma.admin.findUnique({ where: { email: b.email } }); if (!a || !await bcrypt.compare(b.password, a.passwordHash)) return res.code(401).send({ error: 'ایمیل یا رمز اشتباه است' }); res.setCookie('admin_token', sign(a.id), adminCookieOptions()); return { admin: safeAdmin(a) }; });
app.post('/api/admin/logout', { preHandler: auth }, async (_req, res) => { res.clearCookie('admin_token', { path: '/' }); return { ok: true }; });
app.get('/api/admin/me', { preHandler: auth }, async (req: any) => ({ admin: safeAdmin(req.admin) }));
app.get('/api/admin/dashboard', { preHandler: auth }, async () => ({ cards: { users: await prisma.user.count(), totalWallet: (await prisma.user.aggregate({ _sum: { walletBalance: true } }))._sum.walletBalance || 0 }, alerts: { providerConfigured: Boolean(process.env.VENICE_API_KEY || process.env.OPENAI_COMPATIBLE_API_KEY) } }));
app.get('/api/admin/models', { preHandler: auth }, async () => ({ providers: await prisma.modelProvider.findMany({ include: { models: true } }), items: await prisma.aIModel.findMany({ include: { provider: true, performance: true }, orderBy: { priority: 'asc' } }) }));
app.post('/api/admin/models', { preHandler: auth }, async (req: any) => { const b = req.body || {}; const provider = await prisma.modelProvider.upsert({ where: { name: b.providerName || b.provider || 'venice' }, update: { enabled: true }, create: { name: b.providerName || b.provider || 'venice', displayName: b.providerDisplayName || 'AI Route', enabled: true, baseUrl: b.baseUrl, apiKeyEnvName: b.apiKeyEnvName } }); return prisma.aIModel.create({ data: { providerId: provider.id, modelId: b.modelId || 'auto', displayName: b.displayName || b.modelId || 'Auto', capabilities: b.capabilities || ['text'], taskTypes: b.taskTypes || ['chat'], safetyProfiles: b.safetyProfiles || ['safe_default'], enabled: b.enabled ?? true } }); });
app.patch('/api/admin/models/:id', { preHandler: auth }, async (req: any) => prisma.aIModel.update({ where: { id: req.params.id }, data: req.body }));
app.get('/api/admin/model-performance', { preHandler: auth }, async () => ({ items: await prisma.modelPerformance.findMany({ include: { model: { include: { provider: true } } } }) }));
app.get('/api/admin/model-router-logs', { preHandler: auth }, async () => ({ items: await prisma.modelRouterLog.findMany({ take: 200, orderBy: { createdAt: 'desc' } }) }));
app.get('/api/admin/conversations', { preHandler: auth }, async (req: any) => ({ items: await prisma.conversationThread.findMany({ where: req.query?.userId ? { userId: String(req.query.userId) } : {}, include: { user: true, messages: { take: 3, orderBy: { createdAt: 'desc' } }, assets: { take: 3, orderBy: { createdAt: 'desc' } } }, take: 100, orderBy: { updatedAt: 'desc' } }) }));
app.get('/api/admin/settings', { preHandler: auth }, async () => ({ items: await prisma.setting.findMany(), defaults: { brandName: 'اوستا', forbiddenCategories: ['sexual_visual', 'minors', 'abuse', 'doxxing', 'self_harm_instructions', 'weapons_wrongdoing', 'malware', 'fraud'] } }));
app.put('/api/admin/settings', { preHandler: auth }, async (req: any) => ({ items: await Promise.all(Object.entries(req.body as any).map(([key, value]) => prisma.setting.upsert({ where: { key }, update: { value: value as any }, create: { key, value: value as any } }))) }));

app.post('/api/bot/user', async (req: any) => { const b = req.body; return prisma.user.upsert({ where: { telegramId: String(b.telegramId) }, update: { username: b.username, firstName: b.firstName, lastName: b.lastName, languageCode: b.languageCode, lastActiveAt: new Date() }, create: { telegramId: String(b.telegramId), username: b.username, firstName: b.firstName, lastName: b.lastName, languageCode: b.languageCode, lastActiveAt: new Date() } }); });
app.get('/api/bot/topup-settings', async () => ({ paymentUrl: await setting('DONATION_PAYMENT_URL', process.env.DONATION_PAYMENT_URL || ''), title: await setting('DONATION_PAYMENT_TITLE', 'افزایش موجودی'), template: await setting('TOPUP_MESSAGE_TEMPLATE', null), minAmount: await setting('TOPUP_MIN_AMOUNT', 0), withdrawalEnabled: await setting('WALLET_WITHDRAWAL_ENABLED', false), adminTelegramIds: String(await setting('ADMIN_TELEGRAM_IDS', '316244055')) }));
app.get('/api/bot/history/:userId', async (req: any) => ({ items: await prisma.aIUsage.findMany({ where: { userId: req.params.userId }, take: 20, orderBy: { createdAt: 'desc' } }) }));
app.get('/api/bot/ledger/:userId', async (req: any) => ({ items: await prisma.walletLedger.findMany({ where: { userId: req.params.userId }, take: 20, orderBy: { createdAt: 'desc' } }) }));
app.get('/api/bot/settings/:userId', async (req: any) => { const u = await prisma.user.findUniqueOrThrow({ where: { id: req.params.userId } }); return { costConfirmationEnabled: u.costConfirmationEnabled, costConfirmationThreshold: u.costConfirmationThreshold ?? defaultThreshold() }; });
app.post('/api/bot/settings/:userId/cost-confirmation', async (req: any) => prisma.user.update({ where: { id: req.params.userId }, data: { costConfirmationEnabled: Boolean(req.body?.enabled), costConfirmationThreshold: req.body?.threshold ?? null } }));
app.post('/api/bot/payment-receipts', async (req: any) => { const b = z.object({ userId: z.string(), telegramFileId: z.string().optional(), telegramMessageId: z.string().optional(), claimedAmount: z.number().int().positive(), note: z.string().optional(), metadata: z.any().optional() }).parse(req.body); const receipt = await prisma.paymentReceipt.create({ data: { userId: b.userId, telegramFileId: b.telegramFileId, telegramMessageId: b.telegramMessageId, claimedAmount: b.claimedAmount, note: b.note, metadata: b.metadata, status: PaymentReceiptStatus.pending } }); return { ok: true, receipt }; });

app.post('/api/bot/payment-receipts/:id/approve', async (req: any) => { const ids = String(await setting('ADMIN_TELEGRAM_IDS', '316244055')).split(',').map(x => x.trim()); const b = z.object({ adminTelegramId: z.string(), approvedAmount: z.number().int().positive().optional() }).parse(req.body || {}); if (!ids.includes(b.adminTelegramId)) return { ok: false, error: 'forbidden' }; const receipt = await prisma.paymentReceipt.findUniqueOrThrow({ where: { id: req.params.id } }); const amount = b.approvedAmount || receipt.claimedAmount || 0; const admin = await prisma.admin.findFirst(); return prisma.$transaction(async tx => { const u = await tx.user.findUniqueOrThrow({ where: { id: receipt.userId } }); const after = u.walletBalance + amount; await tx.user.update({ where: { id: u.id }, data: { walletBalance: after } }); await tx.walletLedger.create({ data: { userId: u.id, type: LedgerType.TOPUP, amount, balanceBefore: u.walletBalance, balanceAfter: after, description: 'شارژ کیف پول با تایید رسید', createdByAdminId: admin?.id, metadata: { paymentReceiptId: receipt.id } } }); const updated = await tx.paymentReceipt.update({ where: { id: receipt.id }, data: { status: 'approved', approvedAmount: amount, reviewedAt: new Date(), reviewedByAdminId: admin?.id } }); return { ok: true, receipt: updated, telegramId: u.telegramId, amount, balance: after }; }); });
app.post('/api/bot/payment-receipts/:id/reject', async (req: any) => { const ids = String(await setting('ADMIN_TELEGRAM_IDS', '316244055')).split(',').map(x => x.trim()); const b = z.object({ adminTelegramId: z.string(), adminNote: z.string().optional() }).parse(req.body || {}); if (!ids.includes(b.adminTelegramId)) return { ok: false, error: 'forbidden' }; const r = await prisma.paymentReceipt.update({ where: { id: req.params.id }, data: { status: 'rejected', adminNote: b.adminNote, reviewedAt: new Date() } }); const u = await prisma.user.findUniqueOrThrow({ where: { id: r.userId } }); return { ok: true, telegramId: u.telegramId, receipt: r }; });
app.get('/api/admin/payment-receipts', { preHandler: auth }, async () => ({ items: await prisma.paymentReceipt.findMany({ take: 200, orderBy: [{ status: 'asc' }, { createdAt: 'desc' }], include: { user: true } }) }));
app.get('/api/admin/users', { preHandler: auth }, async () => ({ items: await prisma.user.findMany({ take: 200, orderBy: { createdAt: 'desc' } }) }));
app.get('/api/admin/usage', { preHandler: auth }, async () => ({ items: await prisma.aIUsage.findMany({ take: 200, orderBy: { createdAt: 'desc' }, include: { user: true } }) }));
app.get('/api/admin/ledger', { preHandler: auth }, async () => ({ items: await prisma.walletLedger.findMany({ take: 200, orderBy: { createdAt: 'desc' }, include: { user: true } }) }));
app.post('/api/bot/admin-credit', async (req: any) => { const ids = String(await setting('ADMIN_TELEGRAM_IDS', '316244055')).split(',').map(x => x.trim()); const b = z.object({ adminTelegramId: z.string(), telegramId: z.string(), amount: z.number().int(), note: z.string().optional() }).parse(req.body); if (!ids.includes(b.adminTelegramId)) return { ok: false, error: 'forbidden' }; const u = await prisma.user.findUniqueOrThrow({ where: { telegramId: b.telegramId } }); return { ok: true, ...(await adjustWallet(prisma, u.id, b.amount, LedgerType.ADMIN_ADJUSTMENT, b.note || 'شارژ دستی')) }; });

app.get('/api/bot/threads', async (req: any) => ({ items: await prisma.conversationThread.findMany({ where: { userId: String(req.query.userId), archived: false }, take: 20, orderBy: [{ pinned: 'desc' }, { updatedAt: 'desc' }] }) }));
app.post('/api/bot/threads', async (req: any) => { const b = z.object({ userId: z.string(), title: z.string().optional(), type: z.string().optional(), safetyProfile: z.string().optional() }).parse(req.body); return { thread: await prisma.conversationThread.create({ data: { userId: b.userId, title: b.title || 'گفت‌وگوی جدید', type: (b.type || 'chat') as any, safetyProfile: b.safetyProfile || 'safe_default' } }) }; });
app.get('/api/bot/threads/:id', async (req: any) => ({ thread: await prisma.conversationThread.findUniqueOrThrow({ where: { id: req.params.id }, include: { messages: { take: 30, orderBy: { createdAt: 'asc' } }, assets: { take: 20, orderBy: { createdAt: 'desc' } } } }) }));
app.post('/api/bot/threads/:id/messages', async (req: any) => ({ message: await prisma.conversationMessage.create({ data: { threadId: req.params.id, userId: req.body.userId, role: req.body.role || 'user', taskType: req.body.taskType || 'chat', text: req.body.text, outputType: req.body.outputType || 'text', outputUrl: req.body.outputUrl, fileName: req.body.fileName, metadata: req.body.metadata } }) }));
app.post('/api/bot/threads/:id/rename', async (req: any) => ({ thread: await prisma.conversationThread.update({ where: { id: req.params.id }, data: { title: String(req.body?.title || 'گفت‌وگو').slice(0, 80) } }) }));
app.post('/api/bot/threads/:id/archive', async (req: any) => ({ thread: await prisma.conversationThread.update({ where: { id: req.params.id }, data: { archived: true } }) }));
app.post('/api/bot/threads/:id/delete', async (req: any) => ({ thread: await prisma.conversationThread.update({ where: { id: req.params.id }, data: { archived: true } }) }));
app.get('/api/bot/assets', async (req: any) => ({ items: await prisma.generatedAsset.findMany({ where: { userId: String(req.query.userId), ...(req.query.threadId ? { threadId: String(req.query.threadId) } : {}) }, take: 50, orderBy: { createdAt: 'desc' } }) }));
app.post('/api/bot/assets/:id/reference', async (req: any) => ({ asset: await prisma.generatedAsset.findUniqueOrThrow({ where: { id: req.params.id } }) }));

app.post('/api/bot/pending-request', async (req: any) => { const b = z.object({ userId: z.string(), telegramId: z.string(), taskType: z.string(), threadId: z.string().optional(), prompt: z.string(), estimatedCost: z.number().int(), selectedModel: z.string(), selectedProvider: z.string().optional(), request: z.any().optional() }).parse(req.body); const data: any = { userId: b.userId, telegramId: b.telegramId, taskType: b.taskType, threadId: b.threadId, prompt: b.prompt, estimatedCost: b.estimatedCost, selectedModel: b.selectedModel, selectedProvider: b.selectedProvider || 'auto', request: b.request, expiresAt: new Date(Date.now() + 15 * 60 * 1000) }; return { ok: true, request: await prisma.pendingBotRequest.upsert({ where: { telegramId: b.telegramId }, update: data, create: data }) }; });
app.get('/api/bot/pending-request/:telegramId', async (req: any) => ({ request: await prisma.pendingBotRequest.findUnique({ where: { telegramId: String(req.params.telegramId) } }) }));
app.post('/api/bot/pending-request/:telegramId/delete', async (req: any) => { await prisma.pendingBotRequest.delete({ where: { telegramId: String(req.params.telegramId) } }).catch(() => null); return { ok: true }; });

app.post('/api/bot/run', async (req: any, res) => { const b = z.object({ userId: z.string(), telegramId: z.string().optional(), threadId: z.string().optional(), taskType: z.string().optional(), prompt: z.string(), confirm: z.boolean().optional(), userPreference: z.string().optional(), safetyProfile: z.string().optional() }).parse(req.body); const user = await prisma.user.findUniqueOrThrow({ where: { id: b.userId } }); const classification = classifier.classify(b.prompt, b.taskType as any); if (classification.blockedReason) { await prisma.modelRouterLog.create({ data: { userId: b.userId, threadId: b.threadId, taskType: classification.taskType as any, promptPreview: promptPreview(b.prompt), classifierResult: classification as any, safetyDecision: { allowed: false, blockedReason: classification.blockedReason }, finalStatus: 'blocked' } }).catch(() => null); return { ok: false, error: 'safety_blocked', message: classification.blockedReason === 'blocked_sexual_visual' ? 'اوستا نمی‌تونه برای محتوای برهنگی یا جنسی تصویر/ویدیو بسازه. می‌تونی یک پرامپت غیرجنسی، هنری یا امن‌تر بفرستی.' : forbiddenMessage, safetyDecision: { allowed: false, blockedReason: classification.blockedReason }, outputPlan: classification.suggestedOutputPlan }; }
  const selected = router.selectModel({ userId: b.userId, threadId: b.threadId, taskType: classification.taskType, prompt: b.prompt, safetyProfile: b.safetyProfile as any, userPreference: b.userPreference as any, models: await registryModels(), walletBalance: user.walletBalance, confirmationThreshold: user.costConfirmationThreshold ?? Number(await setting('defaultCostConfirmationThreshold', defaultThreshold())) });
  await prisma.modelRouterLog.create({ data: { userId: b.userId, threadId: b.threadId, taskType: classification.taskType as any, promptPreview: promptPreview(b.prompt), classifierResult: classification as any, selectedProvider: selected.provider || undefined, selectedModel: selected.model || undefined, fallbackCandidates: selected.fallbackCandidates as any, reason: selected.reason, estimatedCost: selected.estimatedCost, safetyDecision: selected.safetyDecision as any, finalStatus: selected.model ? 'selected' : 'failed' } }).catch(() => null);
  if (!selected.model || !selected.provider) return { ok: false, error: 'no_model', message: friendlyNoModelMessage };
  const estimate = await calculatePrice(prisma, classification.taskType as any, selected.estimatedCost || 250).catch(() => selected.estimatedCost || 1000); if (user.walletBalance < estimate) return { ok: false, error: 'insufficient', estimate, balance: user.walletBalance };
  const threshold = user.costConfirmationThreshold ?? Number(await setting('defaultCostConfirmationThreshold', defaultThreshold())); const needsConfirm = user.costConfirmationEnabled && estimate > threshold; if (needsConfirm && !b.confirm) return { ok: true, confirmRequired: true, min: estimate, max: Math.ceil(estimate * 1.2), threshold, taskType: classification.taskType, model: selected.model, provider: selected.provider, outputPlan: selected.outputPlan };
  const thread = await ensureThread(b.userId, b.prompt, classification.taskType, b.threadId, b.safetyProfile || classification.requestedSafetyProfile); await prisma.conversationMessage.create({ data: { threadId: thread.id, userId: b.userId, role: 'user', taskType: classification.taskType as any, text: b.prompt, outputType: 'text' } });
  const usage = await prisma.aIUsage.create({ data: { userId: b.userId, taskType: classification.taskType as any, status: 'pending', userPromptPreview: promptPreview(b.prompt), internalProvider: selected.provider, internalModel: selected.model, estimatedCost: estimate, confirmationRequired: needsConfirm, confirmed: Boolean(b.confirm) } });
  try { const ai = getAIProvider(selected.provider, selected.model) as any; if (classification.taskType === 'video') { await reserve(prisma, b.userId, estimate, 'رزرو هزینه ساخت ویدیو'); const v = await ai.createVideoJob({ prompt: b.prompt, model: selected.model }); const job = await prisma.aIJob.create({ data: { userId: b.userId, taskType: 'video', status: 'processing', provider: selected.provider, model: selected.model, externalJobId: v.jobId, prompt: b.prompt, reservedAmount: estimate, metadata: v.raw || undefined } }); await prisma.aIUsage.update({ where: { id: usage.id }, data: { status: 'completed', reservedAmount: estimate, usageMetadata: { jobId: job.id, queue_id: v.jobId } } }); return { ok: true, type: 'video', threadId: thread.id, outputPlan: 'telegram_video', jobId: job.id, message: 'درخواست ویدیو ثبت شد. وقتی آماده شد همین‌جا می‌فرستم.', balance: (await prisma.user.findUniqueOrThrow({ where: { id: b.userId } })).walletBalance }; }
    const r = classification.taskType === 'image' ? await ai.generateImage({ prompt: b.prompt, model: selected.model }) : await ai.generateText({ prompt: b.prompt, model: selected.model, locale: user.languageCode || 'fa-IR' }); const cost = await calculatePrice(prisma, classification.taskType as any, r.providerCost?.amountToman || selected.estimatedCost || 250).catch(() => estimate); const balance = await chargeSuccessful(b.userId, usage.id, classification.taskType, cost, r.providerCost?.amountToman || 0, classification.taskType === 'image' ? 'هزینه ساخت تصویر' : 'هزینه گفت‌وگو با اوستا');
    const assistant = await prisma.conversationMessage.create({ data: { threadId: thread.id, userId: b.userId, role: 'assistant', taskType: classification.taskType as any, text: r.text || undefined, outputType: classification.taskType === 'image' ? 'image' : classification.needsCode ? 'code' : classification.needsFile ? 'file' : 'text', outputUrl: r.imageUrl || undefined, modelProvider: selected.provider, modelId: selected.model, aiUsageId: usage.id, metadata: r.usage || undefined } });
    if (classification.taskType === 'image' && r.imageUrl) await prisma.generatedAsset.create({ data: { userId: b.userId, threadId: thread.id, messageId: assistant.id, taskType: 'image', assetType: 'image', url: r.imageUrl, prompt: b.prompt, modelProvider: selected.provider, modelId: selected.model, metadata: r.usage || undefined } });
    return classification.taskType === 'image' ? { ok: true, type: 'image', threadId: thread.id, outputPlan: 'telegram_photo', url: r.imageUrl, cost, balance, message: 'تصویر آماده شد.' } : { ok: true, type: 'chat', threadId: thread.id, outputPlan: selected.outputPlan, text: r.text, cost, balance };
  } catch (e: any) { if (classification.taskType === 'video') await refund(prisma, b.userId, estimate, 'برگشت رزرو هزینه به دلیل خطا').catch(() => null); await prisma.aIUsage.update({ where: { id: usage.id }, data: { status: 'failed', finalUserCharge: 0, errorMessage: trunc(e) } }).catch(() => null); return res.code(503).send({ ok: false, error: 'provider_unavailable', message: 'اوستا یه لحظه اتصالش رو از دست داد. چند ثانیه دیگه دوباره امتحان کن.' }); }
});

app.post('/api/jobs/video/poll', async () => ({ ok: true, results: [] }));
if (process.env.NODE_ENV !== 'test') app.listen({ port: 4000, host: '0.0.0.0' });
export { app };
